name: Telegram Notifier

on:
  pull_request:
    types: [opened, review_requested]
  push:
    branches:
      - main

jobs:
  notification:
    runs-on: ubuntu-latest

    steps:
      # Send a telegram message on pr open or review request or push commits
      - name: Send events to telegram
        uses: shukhratabdurazakov/telegram-action@master
        with: 
          bot_token: '${{ secrets.BotToken }}'
          chat_id: '${{ secrets.CHATID }}'
